name: seal_ui_example
description: Example app for the Seal UI Design System.
publish_to: 'none'

environment:
  sdk: ^3.11.1
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  seal_ui:
    path: ../
  shadcn_ui: ^0.52.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  widgetbook: ^3.10.0
  widgetbook_documentation_addon: ^1.0.1+2

flutter:
  assets:
    - assets/markdown/components/buttons/sealfilledbutton/
    - assets/markdown/components/buttons/sealoutlinebutton/
    - assets/markdown/components/buttons/sealtextbutton/
    - assets/markdown/components/buttons/sealfillediconbutton/
    - assets/markdown/components/buttons/sealoutlineiconbutton/
    - assets/markdown/components/buttons/sealiconbutton/
    - assets/markdown/components/inputs/sealcalendar/
    - assets/markdown/components/inputs/sealdatepicker/
    - assets/markdown/components/inputs/sealtimepicker/
    - assets/markdown/components/inputs/sealcheckbox/
    - assets/markdown/components/inputs/sealinputotp/
    - assets/markdown/components/inputs/sealradiogroup/
    - assets/markdown/components/inputs/sealselect/
    - assets/markdown/components/inputs/sealslider/
    - assets/markdown/components/inputs/sealswitch/
    - assets/markdown/components/inputs/sealtextarea/
    - assets/markdown/components/inputs/sealtextfield/
    - assets/markdown/components/overlay/sealdialog/
    - assets/markdown/components/overlay/sealpopover/
    - assets/markdown/components/overlay/sealsheet/
    - assets/markdown/components/interaction/sealtooltip/
    - assets/markdown/components/feedback/sealprogress/
    - assets/markdown/components/feedback/sealloader/
    - assets/markdown/components/feedback/sealsnackbar/
    - assets/markdown/layout/accordion/sealaccordion/
    - assets/markdown/layout/breadcrumb/sealbreadcrumb/
    - assets/markdown/layout/avatars/sealavatar/
    - assets/markdown/layout/badges/sealbadge/
    - assets/markdown/layout/cards/sealcard/
    - assets/markdown/layout/tabs/sealtabs/
    - assets/markdown/layout/containers/sealcontainer/
    - assets/markdown/layout/spacing/spacing-scale/
