sonar.projectKey=nayadev_seal_ui_flutter
sonar.organization=nayadev
sonar.projectName=seal_ui_flutter
sonar.sources=lib
sonar.tests=test
sonar.language=dart
sonar.dart.analysis.options=analysis_options.yaml
sonar.dart.lcov.reportPaths=coverage/lcov.info
